### ISSUE TITLE
BulkDetails

### ISSUE THREAD

**Issue by dimmduh** [yeriomin/play-store-api#10]
It seems bulk details request does not work anymore.

**Comment by yeriomin** [comment]
Just checked. It does. Make sure your auth info is correct: bulk details returns an empty list instead of a 401 error if your auth info is incorrect.

**Comment by dimmduh** [comment]
It seems bul request does not work correct now.
It returns "partial" result. I requested 10 apps, but it returns only 2 apps, other 8 is empty.
Check the screen from fiddler
https://yadi.sk/i/Nnp-5HN_3PptGb

**Comment by yeriomin** [comment]
This might be an issue with the current device specified by `X-DFE-Device-Id` or the current account. If for some reason Google decides the app you are requesting should be unavailable to you or is incompatible with your device, it won't return this app in search/bulkDetails/anywhere.

In official Play Store app bulkDetails is used to check for updates. If used for the same purpose, it works as I would expect it to work.
