### ISSUE TITLE
Can not get download url

### ISSUE THREAD

**Issue by camby** [yeriomin/play-store-api#11]

**Comment by yaoxiu** [comment]
Dear yeriomin,
thanks you support play store api. i had an issue when use it . i can not get download url when execute purchase or delivery function for free app. that app not installed via play store. if  installed the app via play store, can got it by delivery function. please tell me why, or how to solve it, thanks.

**Comment by yeriomin** [comment]
@yaoxiu Hello.

This might depend on device definition you use. Generally, the download link is returned in the `delivery` response, but sometimes you need to call `purchase` first. To support all devices you should call `purchase`, check if the download link is returned, and if not, call `delivery`.
