### ISSUE TITLE
Cannot use token + gsfId in the reauth flow

### ISSUE THREAD

**Issue by ruimateus** [yeriomin/play-store-api#13]
When using:
```java
PlayStoreApiBuilder builder = new PlayStoreApiBuilder()
.setHttpClient(new OkHttpClientAdapter())
.setDeviceInfoProvider(deviceInfoProvider)
.setToken(token)
.setGsfId(gsfid);
GooglePlayAPI api = builder.build();
```

It will throw 

`
com.github.yeriomin.playstoreapi.ApiBuilderException: Either email-password pair or a token dispenser url is required
`

How can we use token and gsfId directly without needing a token dispenser?

**Comment by yeriomin** [comment]
Fixed in master, see tests.

If you want a workaround, GooglePlayAPI has setters for token and gsfId.
