### ISSUE TITLE
how to get content rating of an App?

### ISSUE THREAD

**Issue by wormcy** [yeriomin/play-store-api#14]
I have tried with following code, the result always be 0.        

```
       DetailsResponse response = null;
       response = api.details("org.amalgam.laboratory");
        AppDetails detail = response.getDocV2().getDetails().getAppDetails();
        System.out.println(detail.getContentRating());
```
Thanks a lot!

**Comment by yeriomin** [comment]
Here: `response.getDocV2().getRelatedLinks().getRated()`

Unfortunately, Play Store API does not provide an integer value. You can get a label which looks like "Rated for 12+" here: `response.getDocV2().getRelatedLinks().getRated().getLabel()`. There is an image there too.

**Comment by wormcy** [comment]
Awesome!! Thanks
