### ISSUE TITLE
How do you build device .properties?

### ISSUE THREAD

**Issue by matlink** [yeriomin/play-store-api#15]
How did you build files located at https://github.com/yeriomin/play-store-api/tree/master/src/main/resources?

**Comment by yeriomin** [comment]
Here:
https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/bugreport/BugReportDeviceInfoBuilder.java

It happens when Yalp Store crashes or the user decides to send feedback.
