### ISSUE TITLE
How to find out the more API, like this

### ISSUE THREAD

**Issue by HxBreak** [yeriomin/play-store-api#16]

**Comment by HxBreak** [comment]
![screenshot_20180414-144156](https://user-images.githubusercontent.com/15846180/38765330-1fb6b56c-3ff2-11e8-8cff-3c2bbd15a384.jpg)
![screenshot_20180414-144139](https://user-images.githubusercontent.com/15846180/38765331-1fe76a9a-3ff2-11e8-9b10-da2536b768ab.jpg)

**Comment by yeriomin** [comment]
I'm sorry, what does "more API" mean?

To get all apps by some developer, search "pub:<developer name here>"
