### ISSUE TITLE
is it possible to login with device that we want?

### ISSUE THREAD

**Issue by jr3074** [yeriomin/play-store-api#17]
for example i want to login using device with Android 6 is it possible?
i use this with your token dispenser and login, it said that i use "oneplus one" device on my google account activity.
if yes, how to config it?
thanks

**Comment by jr3074** [comment]
well, now i know why i get "oneplus one", i use [gplaycli](https://github.com/matlink/gplaycli) and there is default value for the device.
but why when i request token dispenser ac2dm (checkin) there isn't activity on my android account?

**Comment by yeriomin** [comment]
The example on this repo's main page uses a definition for Sony Xperia Z1 (device-honami.properties). You can find more device definitions here: https://github.com/yeriomin/play-store-api/tree/alldevices/src/main/resources
