### ISSUE TITLE
bulkDetails response is empty

### ISSUE THREAD

**Issue by anod** [yeriomin/play-store-api#18]
Hi

BulkDetailsResponse is success, but empty.

> packageNames size = 324
>
> I/DebugHttpClientAdapter: Requesting https://android.clients.google.com/fdfe/bulkDetails
> I/DebugHttpClientAdapter: HTTP result code 200
>
> result = {BulkDetailsResponse@5331} 
>  entry_ = {ProtobufArrayList@5334}  size = 0
>  memoizedSerializedSize = -1
>  unknownFields = {UnknownFieldSetLite@5335} 
>  memoizedHashCode = 0
>  shadow$_klass_ = {Class@5332} ""
>  shadow$_monitor_ = -2050010224

Other APIs like search and details are working.

Did you notice this one? Do you think there is may be a throttle?

**Comment by yeriomin** [comment]
> Did you notice this one?

Yep.

> Do you think there is may be a throttle?

No, just an API change.

**Comment by anod** [comment]
Request format was changed, this worked for me:
  ```

    message BulkDetailsRequestDocProperties
    {
    }

    message BulkDetailsRequestDoc
    {
        required string docid = 1;
        required int32 versionCode = 2;
        required int32 num2 = 3;
        required BulkDetailsRequestDocProperties properties = 7;
    }

    message BulkDetailsRequest
    {
        repeated BulkDetailsRequestDoc docs = 8;
    }

```
In addition I had to update "x-dfe-encoded-targets" header as well:

`"CAESjALBlYEGpgrRAkLwA5IHgAKkCLUBWEDUBTKSAekKmAG6ATKGAS9o8gLdASfcARb7C7gDAQLPBa4DzxPRCLwB2xC2AQGlA54DMCjjC8MCowKtA7AC9AOvDbgC0wHfBlcBxQTLAVGDAxdu9gHlAUyIAhgC5QECxwEHYkJLYgHXCg2hBNwBQE4BYROnAl0y8wKiAoADzQK2AasEyAHeBArIApMCYgnaAmwP6wIxASLNAuYBhgK/Ad0BDhO5AaoBwQMD1wIcB6UBAcUBOgED8wGXAgEH5QGWBANGDgjrAcoBV8kB5QEFHOwCZ5sBlAKQAjjfAgElbI4KkwVwRYQINcwBKtAB3wk2RfoFnALeBvMGGowHEgEBAQTYAQ0ttgFhSlcCAwRrN4DTzwKCu7EDAQEDAgQJCAkBAggEAQIBAQYBAQMFBBUGAwUEBAQDAQ8CAQIDxwEBFgQPJsEBfS8CHAEBCpABDDMXASEKFA8GByI3hAEODBZNCVIBBX8RERgBA4sBGGkUECMIEXBkEQ9qnwHEAoQBBIgBigEZGAsrEwMWBQcBKmUCAiUocxQnLfQEMQ43GIUBjQG0AVlCjgEeJwskECYvW9QBYnoJAQreAXmqAQwDLGSeAQSBAXRQRdQBigHMAgUFCc0BBAFFoAE53wJgNS7OAQ1yqwEgiwM/+wImlwMeQ60ChAZ24wX2Aw8HAQL2AxZznAFVbQEJPAHeBSAQDntVXpsHKxjYAQEhAQcCIAgSHQemAzgBGkaEAQG7AnWnARgBIgKjAhIBARgWD8YLHYABhwGEAsoBAQIBwwEn6wIBOQHbAVLnA0H1AsIBdQETKQSLAbIDSpsBBhI/RDgUK1VF4gKDAgsMCC9cF1EbuQEO9wG3ASrnA98DlwEE6wGHAWIVGdMBBhMSC1ooJAECAoQFtQENBiNZKJ8BMh4YAQQgAlYBIwKQAR0SGyd+iQFdDA/9AUkjBCIqHoACPwQbAxcg3AE9sgHKAgsYsQIlfhtauwEMiAEjeYsBigEDOwErBTcCVAFipAIhMQ1FA54DzgHmAimUBAvsAQc4jAEeDP8DAQK1AWtsOlAKCAKKBBQUAgMBMTJRGgIDygGZAToBAQcBVYQBlwPJAWkIfYkBdw5eMhE03gFGRsECBA89YREcP4kBHCdRBleRATIBCgGdAtICBBJNJQKIAYcBhgEgMpACEcYBBQQCBgQCBAIHBAIEAgUGBAIHBgQBBwYEAgQBBiLUAX5VOSEkH14BAQUDKQGkAXQFBwUEAwICmwHtAoUCBQQCBgcVAisdFAIKAb4BCDoWFChoJoYCGwM9LocBAwERmQEEEgsCRNcBPCG0AQ4BV3EBCV0gFQoFFxqSASoBLB4vCB4DRwgJiwEUCX4E2gEFBgcFBwQCBQYEAz8OJAQDBAEEAwYEH5EBtAMmBzsCAwICAgECE10QDBhVqQEDAgMFAQIJJw5YASEJCiEtOg4KLBQsFAcmJTSdAXoEAQcEAgQBMjMkFitdHqECJwooAwEuGS8FAgIBAwICRhwaAcMBCKMDBQUaUaQBDMUBDCAVbzkFAhYJJBYEAgQDBgU"`

**Comment by yeriomin** [comment]
Thanks for sharing. Updating "x-dfe-encoded-targets" was enough for me.
