### ISSUE TITLE
The last fix broke categories.

### ISSUE THREAD

**Issue by alexandrumarcel** [yeriomin/play-store-api#19]
The commit that fixes apps updatrs broke the categories so we can't sort the apps by their category

https://github.com/yeriomin/play-store-api/commit/686268d25913402d2761ba3e5778b028f3ed5606

**Comment by yeriomin** [comment]
Added new category list methods here https://github.com/yeriomin/play-store-api/commit/8dcfa71e6431936de5c2f6d8780fa9509e76d747
