### ISSUE TITLE
Wrong sdk 

### ISSUE THREAD

**Issue by marat1995** [yeriomin/play-store-api#2]
Привет.
В Yalp есть возможность выбрать устройство Samsung Galaxy Tab 10.1
Я пишу с него как раз.
В скобках указано 21 апи.
Наверное это ошибка. У меня tab 10.1(3g версия), андроид 5.0.2, SDK 21.
Исправьте номер sdk пожалуйста.

**Comment by yeriomin** [comment]
Нет, это не ошибка. На вашем устройстве может быть поставлена любая версия Android вплоть до 25.

Для работы с API Google Play нужно отправить немало информации об устройстве (загляните [сюда](https://github.com/yeriomin/play-store-api/blob/master/src/main/resources/device-gtp7510.properties)). Модель устройства и версия установленной ОС это вещи по которым пользователь может *предположить* всё остальное, поэтому именно они выводятся в интерфейсе.
