### ISSUE TITLE
translatedDescriptionHtml

### ISSUE THREAD

**Issue by Attect** [yeriomin/play-store-api#20]
how can I get it? It's a translated version text of description with given local.
Thanks.

**Comment by yeriomin** [comment]
It is always translated as far as I know. If you supply the locale to the api wrapper and if the description is translated by the app developer (you can see in in Play Store app),   descriptionHtml will contain translated description.

**Comment by Attect** [comment]
I use this:

```
deviceInfoProvider.setLocaleString(Locale.CHINA.toString());
```

And try to find translate from here
DetailsTask.java
```
protected App getResult(GooglePlayAPI api, String... arguments) throws IOException {
        DetailsResponse response = api.details(packageName);
        Log.d("DEBUG","description:" + response.getDocV2().getDescriptionHtml());

```
It seem to doesn't containt translate text.

**Comment by yeriomin** [comment]
Like I said: 

>  if the description is translated by the app developer (you can see in in Play Store app)

Is it translated in the Play Store app?

Try

    api.setLocale(Locale.CHINA);

**Comment by Attect** [comment]
Sorry,my mistake
translatedDescriptionHtml  is translated content  by Google Translate,not translate by app author.
I have been find this field in https://github.com/dweinstein/node-google-play

**Comment by IRGC** [comment]
in the DocV2 expect translated description at position 23 
example add line to your .proto file 
`optional string translatedDescriptionHtml = 23;`

for some language descriptionHtml itself contain the requested language. 
so first check `translatedDescriptionHtml` is empty or not.
