### ISSUE TITLE
A default HttpClientAdaptor

### ISSUE THREAD

**Issue by HungUnicorn** [yeriomin/play-store-api#23]
hi,

I found this OkHttpClientAdaptor is package private. would it be better to have a default one?

https://github.com/yeriomin/play-store-api/blob/master/src/test/java/com/github/yeriomin/playstoreapi/OkHttpClientAdapter.java

**Comment by yeriomin** [comment]
Hello.

No, that would require making some http library a dependency. Forcing a dependency is not a good idea. The whole point of https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/HttpClientAdapter.java is to let the developer choose whatever http library he wants.
