### ISSUE TITLE
sale info is missing

### ISSUE THREAD

**Issue by segoby** [yeriomin/play-store-api#28]
Until a few days ago `saleEndTimestamp` returned a timestamp when the sale ended. Now it only returns 0.

**Comment by yeriomin** [comment]
Not for me. Maybe the app you are getting info about is different from the others. Indefinite sale?

If nothing changed on your side it means the API has changed. And even if it was really happening, I don't own Google ;) so there is no way for me to make their API to return what I/you want, sorry.

Can't say anything more specific unless you provide at least the package name which you want info about.

**Comment by segoby** [comment]
Funny enough the information is now showing up without having changed anything. Maybe there was an error on googles side.
Thank you
