### ISSUE TITLE
Add if app is now free?

### ISSUE THREAD

**Issue by mostmaz** [yeriomin/play-store-api#4]
hi
thank you for this api it is very useful
can you please add a way to get if the app is now free?
some apps goes from paid to free for certain period , is there a way to check if the is free now?

**Comment by yeriomin** [comment]
Hello. I do it like this:

```java
    static public boolean isFree(DocV2 details) {
        if (details.getOfferCount() > 0) {
            return details.getOffer(0).getMicros() == 0;
        }
        return false;
    }
```

**Comment by mostmaz** [comment]
Can you please give me an example ?

i do like this to get app package name :

String apppackagename = app.getPackageName();

how to do the same for getting offer is free or paid like you did above?

**Comment by mostmaz** [comment]
Please?

**Comment by mostmaz** [comment]
I got it , thankyou
