### ISSUE TITLE
Possible to share a implementation of HTTPClientAdapter?

### ISSUE THREAD

**Issue by johneffort** [yeriomin/play-store-api#44]
I notice that there is no implementation of a HTTPClientAdapter? Documentation is a bit scarce for the interface methods that needs implementation. Any reason a sample is not available?

**Comment by HxBreak** [comment]
here https://github.com/yeriomin/play-store-api/blob/master/src/test/java/com/github/yeriomin/playstoreapi/OkHttpClientAdapter.java

**Comment by johneffort** [comment]
Thanks!
