### ISSUE TITLE
Can't retrieve VersionString when request with bulkDetails.

### ISSUE THREAD

**Issue by longdt03** [yeriomin/play-store-api#9]
Hi,

I'm very thankful for your library. It work very well. But, I'm using the latest version (0.26) and it have a little issue. When I request detail of multiple package name with bulkDetails then I get versionString of each but nothing to return.
Please fix it. I waiting for new version. Thank you!

**Comment by yeriomin** [comment]
Hello.

This is how Google API works. Impossible to fix on our side. Sorry.
